### ISSUE TITLE
Default value not populated

### ISSUE THREAD

**Issue by kevinkam** [Airtable/airtable.js#139] opened 2019-10-18 01:55 UTC
I have set default value on my Airtable column, but if I create a record via javascript API, it won't automatically populate the default value on the new record, it only have the values that I pass to airtable, should I pass those field got default value one with a `null` value or what?

**Comment by EvanHahn** [comment] 2019-10-21 18:33
This is working as intended, though I think it's a bit confusing. Default values don't apply to records created with the API.

I'm going to close this because things are working as expected, but feel free to discuss further or open a new issue if you have unrelated questions.

**Closed by EvanHahn** 2019-10-21 18:33 UTC
