### ISSUE TITLE
Add TS type definitions?

### ISSUE THREAD

**Issue by kopertop** [Airtable/airtable.js#34] opened 2017-09-15 15:34 UTC
It would be great to see Type definitions added (.d.ts files) to support TypeScript typings.

**Comment by s16h** [comment] 2018-03-30 22:02
Any plans to do this?

**Comment by rascode** [comment] 2018-06-12 15:37
Same issue here.  Trying to use Airtable with Typescript but failing during compile.

**Comment by ukaric** [comment] 2019-02-26 22:47
Yeah typings should be created by now.

**Comment by EvanHahn** [comment] 2019-02-27 21:34
This is a good idea. We'll review pull requests adding type definitions to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/). Their readme has [detailed instructions showing how to do this](https://github.com/DefinitelyTyped/DefinitelyTyped/#how-can-i-contribute).

Please add me (@EvanHahn) as a reviewer and I'll take a look. I've reviewed a few other DefinitelyTyped PRs and am happy to look at another.

Because we don't intend to add type definitions in this repo, I'm going to close this issue, but again—I'm more than happy to review contributions to DefinitelyTyped.

**Closed by EvanHahn** 2019-02-27 21:34 UTC

**Comment by lookfirst** [comment] 2019-06-18 06:55
This shouldn't have been closed. The types are incomplete.

**Comment by EvanHahn** [comment] 2019-06-18 14:20
I closed the issue because we don't intend to add type definitions to Airtable.js, at least for now. However, I'm more than happy to review DefinitelyTyped PRs!

How are the types incomplete?

**Comment by lookfirst** [comment] 2019-06-18 14:23
> I closed the issue because we don't intend to add type definitions to Airtable.js

That is sad face.

> How are the types incomplete?

It only supports query operations, not the rest of crud.

**Comment by EvanHahn** [comment] 2019-06-24 15:17
If there's an issue with `@types/airtable`, there should be a [issue in the DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/issues). Happy to aid in filing that if helpful!

**Comment by lookfirst** [comment] 2019-06-24 15:26
i just did it on my own. sorry, i don't have time to work for your company for free.

if you want to offer a complete product, you should have proper type definitions, which is what this issue is tracking. the closed state and pushing off to DT, implies a lack of care for it.

typescripts popularity is growing all the time. it is a loss for your customers to not provide good support for it.

good luck.

**Comment by EvanHahn** [comment] 2019-06-24 21:46
@lookfirst Thanks for this feedback—sorry it left a bad taste.

We don't intend to add TypeScript type definitions to Airtable.js right now. Not because we don't think it's useful, but because we don't think it's as important as other things, such as adding batch operations to the API. (And to Airtable.js!)

We've got a broad set of users and have to prioritize carefully across many different fronts. Again, sorry this doesn't feel right to you—I hope this helps explain our motivation.

**Comment by margolisj** [comment] 2019-10-16 16:43
Hi @EvanHahn, There are types currently available for 5.something. I'm using Airtable heavily right now and not having TS typings is annoying at best. I'd be interested in updating them for 7.x if you guys could pick it up and own it after that. Updating them lock step with updating your API would only add a few minutes of dev time per change.

While I agree with @lookfirst, I understand you guys have other priorities and I'm willing to temporarily bit the bullet. I think not prioritizing probably about 2hr bit of work over two years, which at least ~50 "power users" are interested in, is probably incorrect but that is your decision to make. Let me know if we can make this work.

**Comment by lookfirst** [comment] 2019-10-17 02:25
@margolisj It sounds like you're going to be building something complicated, so I want to jump in and give you some advice from someone who tried already...

Airtable is a very very very nice website and works great that way because there is immediate feedback... the user can 'see' the problem right away... but accessing it via API will only leave you with disappointment when you start to lose data or wonder why strange things are happening. It just isn't transactional enough for that sort of usecase and you'll end up writing a lot of code to just make sure that things are ok.

The 5 RPS should be a dead giveaway that they don't want anyone using their API.

**Comment by margolisj** [comment] 2019-10-17 16:57
@lookfirst I totally agree but I'm already writing code using this as a "database". I just want to have the functions stubbed out so I can sanely use typescript. There will be a lot of any types floating around. What is weird to me is they have typed fields but that doesn't translate to much.

All I want is that these will be picked up and owned while they make changes. I couldn't imagine writing a production public library without either providing typings or writing it in typescript.

**Comment by lookfirst** [comment] 2019-10-18 02:39
> I'm already writing code using this as a "database".

That is exactly what I'm telling you... don't do that. Stop. Turn around. Run away. It will not work.

![image](https://user-images.githubusercontent.com/85355/67061661-241ae000-f18b-11e9-91c4-4829bf905cb8.png)

**Comment by EvanHahn** [comment] 2019-10-21 16:51
> I'd be interested in updating them for 7.x if you guys could pick it up and own it after that. Updating them lock step with updating your API would only add a few minutes of dev time per change.

@margolisj Would you be able to do that upfront work in the DefinitelyTyped repository? The only difference is where the types live—do they live in this repo, or there? Do they live in `@types/airtable`, or in the `airtable` package itself?

> The 5 RPS should be a dead giveaway that they don't want anyone using their API.

Trust me—I want people using our API! I understand why this is limiting for a lot of use cases. I'd love to increase that limit, but when we look at all of the things our small team has to do, we have to acknowledge that we can't do everything.

To reiterate, we don't intend to add TypeScript type definitions to this repo, but I'm happy to help getting them added to DefinitelyTyped.

**Comment by lookfirst** [comment] 2019-10-22 00:29
The absolute lowest barrier to entry for developers is to just include one project. By saying you don't intend to keep them here, also means that you don't intend to support or acknowledge them.

Keeping the typings in here, makes contribution easier as well. No need to go here, figure out they are in DT, then go to DT, figure out how to contribute to DT, clone that repo, blah blah blah.

Have you ever contributed to typings in DT? You get added to a list of creators for that typing and then spammed for the rest of your life, every time someone else proposes a change. Obviously that can all be silenced, but trust me, it isn't fun to deal with. The *only* benefit DT provides is that there is more eyes on the typings.

> Trust me—I want people using our API!

Given the state of the API and the RPS limitations, I don't think you should encourage anyone to use it, except as read-only. The write API is inherently unsafe due to the lack of transactional integrity. In my testing, I had many writes just randomly not appear.

> our small team

Didn't you just get $100m in funding?!? Congrats on that for sure!

**Comment by margolisj** [comment] 2019-10-22 22:03
> To reiterate, we don't intend to add TypeScript type definitions to this repo, but I'm happy to help getting them added to DefinitelyTyped.

Why would you want them in DT instead of here? I'm asking that you guys update them when you make changes such that this work isn't in vain and so I'd rather have them live here instead of forgotten in DT. Also, most libraries have gone away from DT so you don't have to have a million `@types/xyz` imports.

**Comment by EvanHahn** [comment] 2019-10-23 17:56
> Why would you want them in DT instead of here?

Speaking for Airtable: we'd prefer them to be in DefinitelyTyped because then the community maintains them. That means less work for us, selfishly, but it also means that the community can respond to changes we don't keep up with, should that happen.

Speaking for myself: I personally maintain two sorta-popular npm modules: [`helmet`](https://helmetjs.github.io/) and [`humanize-duration`](https://github.com/EvanHahn/HumanizeDuration.js). Combined, they had over 800,000 downloads in the week (small compared to Express's 10 million!).

I'm working on adding TypeScript support to Helmet and while it's mostly done, it's a drag, and I don't enjoy the work. I'm much happier with what I've done with `humanize-duration`: put it in DefinitelyTyped, and be responsive to PRs there. It helps me iterate more quickly, and cuts down on the amount of extra tooling required just to build the simple module.

Again, that's my personal stance and is somewhat separate from Airtable's, but I _do_ work for Airtable and have been the primary maintainer of Airtable.js recently.

> I'd rather have them live here instead of forgotten in DT.

Could you give some examples of modules that have languished in DefinitelyTyped? I've personally found their maintainer alerts to be pretty helpful.

> Also, most libraries have gone away from DT

Is this true? I'd be curious to know for my own knowledge. It's unscientific, but I took a quick look at the 7 [most-depended-on npm packages](https://www.npmjs.com/browse/depended). Moment, Commander, Chalk have typings built-in; Lodash, React, Express, and Request do not appear to.

---

Again, **I am more than happy to review any changes to Airtable's type definition in DefinitelyTyped**.

**Comment by bkniffler** [comment] 2020-05-19 07:16
Well, I don't enjoy using Airtable with Typescript. Mostly because the Typescript definitions seem out of sync with the docs (e.g. use of callbacks in docs vs no callbacks in typedefs; or arrays in create as first arg vs single object as first arg in typedefs; ). The issue is, I can't trust the Typescript definitions if there is no guarantee that they are up-to-date and if there is no testing around. So now I'm dealing with your docs, copy and pasting examples, finding they don't conform to types and try and figure what's the correct usage. Its really a big pain to work with.

I see your point with free open source libraries, and I'm super grateful to you, personally, since I've been using helmet and its been great. But Airtable is part of a commercial service, and I expect a different level of code sanity from it, especially considering the ever rising popularity of Typescript.

**Comment by Vadorequest** [comment] 2020-06-02 16:13
If I were an official maintainer, I'd seriously reconsider migrating the whole Airtable API to TS altogether, you won't even bother having to maintain a set of defs, it'll be included within the lib itself and will automatically evolve alongside it.

Also, as mentioned above, it is true that most _professional_ libs are indeed moving away from DT, for the reason cited above: They're migrating their codebase to TS and don't need an out-of-sync DT anymore.

I've been using TS since 2013, and that's what I can tell, from experience.
You'd also benefit from this, as your base code would become more maintainable.

I was hesitating using the official airtable.js lib for https://github.com/UnlyEd/next-right-now, but it's clear now that I'll rather rebuild something myself with proper typedefs. (I don't need all the capabilities you offer, and want it as light as possible, typedefs aren't my only consideration)

**Comment by domdomegg** [comment] 2024-04-26 00:19
FYI I made a wrapper around the airtable library that's called [`airtable-ts`](https://www.npmjs.com/package/airtable-ts) because I got so frustrated by the default airtable library's TypeScript support.

It actually gives you much more in depth type safety: including typing the tables and fields etc. Would be keen for feedback as to how people find it.
