### ISSUE TITLE
CORS Issue with update

### ISSUE THREAD

**Issue by TheMkrage** [Airtable/airtable.js#284] opened 2021-10-02 19:40 UTC
Hi!

I am using airtable: `"^0.11.1",` with my frontend react app. Everything works fine and I am able to create and list records out. But when I try to use the update functionality, I run into a CORS issue regarding PATCH requests specifically:

`Access to fetch at 'https://api.airtable.com/v0/appfGOrSlohKglsao/Users/?' from origin 'http://localhost:3000' has been blocked by CORS policy: Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.
run_action.ts:67 PATCH https://api.airtable.com/v0/appfGOrSlohKglsao/Users/? net::ERR_FAILED`

`N2Sbase('Users').update([
                    {
                        "id": records[0].id,
                        "fields": fields
                    }
                ])`

Am I missing some configuration? It seems like Airtable blocks on patch requests for some reason

**Comment by albreyb** [comment] 2022-02-24 18:54
Hey there, thank you for your question. We are currently investigating this internally. I'll respond once I have the right answer.

**Comment by jflachapelle** [comment] 2023-12-16 15:42
Is this fixed? Our team (all working remotely, tried on different devices, OS, browsers) does not get any CORS error but our client gets the same issue as above with:  ..../Scores?view=Grid+view&pageSize=10

_Response preflight request doesn't pass access control check ..etc._

version is 0.12.2

**Comment by DannyMatteson-at** [comment] 2024-12-11 19:17
Thank you for your patience and contributions. We were unable to reproduce the CORS issue with PATCH requests, but it could be a legitimate problem if it is still occurring. If you continue to experience this issue, please provide updated reproduction steps using our official support channel. You can contact Airtable support for assistance by visiting [Airtable Support](https://support.airtable.com/doc/) and clicking the black chat bubble in the bottom right corner. We will now close this issue.

**Closed by DannyMatteson-at** 2024-12-11 19:17 UTC
Labels: further investigation, escalated internally
